config/routes.rb
Rails.application.routes.draw do
  get 'register/metodoregister'
  get 'login/metodologin'
  get 'home/metodohome'
  get 'delete/metododelete'
  get 'home/index'
  get 'cart/metodocart'
  get 'home', to: 'home#metodohome'
  get 'add', to: 'add#metodoadd'
  get 'modif', to: 'modif#metodomodif'
  get 'verify', to: 'verify#metodoverify'

  get 'data_sales' , to: 'data_sales#metodods'
  get 'report' , to: 'report#metodorep'

  get 'cart', to: 'cart#metodocart'

  get 'venta_semanal', to: 'venta_semanal#metodoventa_semanal'



  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  #match ':controller(/:action(/:id))(.:format)'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/models/sale_detail.rb
class SaleDetail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/add_controller.rb
class AddController < ApplicationController
  def metodoadd
  	@nombre = params[:name]
  	@stock = params[:stock]
  	@codigo = params[:code]
  	@precio = params[:price]
  	@tipo = params[:type]
  	@id_usuario = current_user.id
  	if @nombre != nil then @producto = Product.create({nombre: @nombre, tipo: @tipo, codigo: @codigo, stock: @stock, precio: @precio, id_usuario: @id_usuario})
  	end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	def metodocart
		@productos = Product.where(id_usuario: current_user.id)

		@codigos = params[:codigo]
		puts(" el codigo es #{@codigos}")
		return if @codigos.blank? 

		@codigosv = @codigos.split(",")
		#puts ("	ESTE ES CODE -----------#{@codigos}")
		 ActiveRecord::Base.transaction do 
			#puts(Product.where(codigo: @codigos).inspect)
			#arreglar haciendo un for
			#Product.where(codigo: @codigosv).each do |codigo|
			@codigosv.each do |codigo|
				a = Product.find_by(codigo: codigo)
				Product.find_by(codigo: codigo).update(stock: a.stock-1)
				#puts("logra entrar al actualizar")
			end
		end
		@monto = 0
			@codigosv.each do |codigo|
				b = Product.find_by(codigo: codigo)
				@monto = @monto + b.precio
				#puts("logra entrar al actualizar")
			end
		Sale.create({codigo: @codigos, monto: @monto, FechaVenta: Date.today, us: current_user.id})
		#codigo.value = codigo.textContent
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def metodologin
  end
end

app/controllers/modif_controller.rb
class ModifController < ApplicationController
  def metodomodif
  end
end

app/helpers/add_helper.rb
module AddHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/data_sales_helper.rb
module DataSalesHelper
end

app/helpers/delete_helper.rb
module DeleteHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/modif_helper.rb
module ModifHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/verify_helper.rb
module VerifyHelper
end

app/views/add/metodoadd.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>




  </head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

      <!-- Main -->
        <div id="main">
          <div class="inner">

            <!-- Header -->
            <header id="header">
              <div class="logo">
                <a >Inventario Online</a>
              </div>
            </header>


              <section class="top-image">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="down-content">
                      <form>
                              <div class="container">
                                <h1>Añadir a inventario</h1>
                                <p>LLena los campos para añadir al inventario.</p>
                                <hr>
                            
                                <label for="name"><b>Nombre</b></label>
                                <input type="text" placeholder="Ingresa el nombre del producto" name="name" required <%= text_field_tag 'name', @nombre %>
                            
                                <label for="stock"><b>Stock</b></label>
                                <input type="text" placeholder="Ingresa el Stock del producto" name="stock" required <%= text_field_tag 'stock', @stock %>
                            
                                <label for="code"><b>Codigo</b></label>
                                <input type="text" placeholder="Ingresa el Codigo del producto" name="code" required <%= text_field_tag 'code', @codigo %>
                            
                                <label for="price"><b>Precio</b></label>
                                <input type="text" placeholder="Ingresa el Precio del producto" name="price" required <%= text_field_tag 'price', @precio %>
                            
                                <label for="type"><b>Tipo De Producto</b></label>
                                <input type="text" placeholder="Ingresa el Tipo de producto" name="type" required <%= text_field_tag 'type', @tipo %>
                          
                                <!--<p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>-->
                            
                                <div class="action" >
                            
                                  <!--<button type="button" class="cancelbtn" >cancelar</button>-->
                                  <!--button class="cancelbtn" onclick="window.location.href='/';">Cancelar</button-->
                                  <button type="submit" class="primary-button" onclick="PopUp()" >Añadir</button>
                                  <button type="reset" class="primary-button" >reset</button>
                                </div>
                              </div>
                            </form>
                    </div>
                  </div>
                </div>
              </div>
            </section>


          </div>
        </div>

      <!-- Sidebar -->
        <div id="sidebar">
          <div class="inner">             
            <!-- Menu -->
            <nav id="menu">
              <ul>
                <li><a href="home">Inicio</a></li>
                <li><a href="add">Añadir Producto</a></li>
                <li><a href="verify">Verificar Inventario</a></li>
                <li><a href="data_sales">Datos Historicos</a></li>
                <li><a href="report">Ventas del dia </a></li>
                <li><a href="venta_semanal">Ventas de la semana </a></li>
                <li><a href="cart">venta</a></li>
                <li><a <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></a></li>
            </nav>
          </div>
        </div>

    </div>


</body>


  </body>

</html>

app/views/cart/metodocart.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>





  </head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

      <!-- Main -->
        <div id="main">
          <div class="inner">

            <!-- Header -->
            <header id="header">
              <div class="logo">
                <a >Inventario Online</a>
              </div>
            </header>

            
            <section class="top-image">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="down-content">
                      <div class="container">
                <div class="row">

                  <button onclick="window.location.reload();" >Iniciar Venta</button>
                  <p hidden="" , style="color: white">
                    <% @productos.each do |p| %>
                  <nombre><%= p.nombre %></nombre>
                  <cod><%= p.codigo %></cod>
                  <precio><%= p.precio %></precio>
                  <% end %>
                    
                  </p>
                 

                  
                 
                  <p id="demo"></p>
                  


                    <!-- Elementos generados a partir del JSON -->
                   <main id="items" class="col-sm-8 row"></main>
                    <!-- Carrito -->
                    <aside class="col-sm-4">
                        <h2>Carrito</h2>
                        <!-- Elementos del carrito -->
                        <ul id="carrito" class="list-group" onkeyup="cart()"></ul>
                        

                        <!-- Precio total -->
                            <p class="text-right">Total: <span id="total"></span>$</p>
                            <%= form_tag cart_metodocart_path, method: :get do %>
                                <%= hidden_field_tag "codigo" %>
                                <button id="boton-vaciar" class="btn btn-danger" >Vaciar</button>
                                <button onclick="PopUp2()" <%= submit_tag "Venta", class: 'primary-button', id: 'boton-venta' %>Venta</button>
                            <% end %>
                            </p>
                </aside>
               </div>
            </div>
                      
                  </div>
                </div>
              </div>
            </section>


          </div>
        </div>

      <!-- Sidebar -->
        <div id="sidebar">
          <div class="inner">             
            <!-- Menu -->
            <nav id="menu">
              <ul>
                <li><a <%= link_to "Inicio",  home_path %></li>
                <li><a <%= link_to "Añadir Producto",  add_path %></li>
                <li><a <%= link_to "Verificar Inventario",  verify_path %></li>
                <li><a <%= link_to "Datos Historicos",  data_sales_path %></li>
                <li><a <%= link_to "Ventas del dia",  report_path %></li>
                <li><a <%= link_to "Ventas de la semana",  venta_semanal_path %></li>  
                <li><a <%= link_to "Venta",  cart_path %></li>
                <li><a <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></a></li>
              </ul>
            </nav>
          </div>
        </div>
    </div>


</body>


  </body>

</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>


  </head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

      <!-- Main -->
        <div id="main">
          <div class="inner">

            <!-- Header -->
            <header id="header">
              <div class="logo">
                <a>Inventario Online</a>
              </div>
            </header>

            <!-- Banner -->
            <section class="main-banner">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="banner-content">
                      <div class="row">
                        <div class="col-md-12">
                          <div class="banner-caption">
                            <h4>Bienvenido a tu <em>Inventario Online</em> </h4>
                            <p>El lugar donde podras trabajar y manejar tu empresa de la mejor manera.</p>
                            
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>


          </div>
        </div>

      <!-- Sidebar -->
        <div id="sidebar">
          <div class="inner">             
            <!-- Menu -->
            <nav id="menu">
              <ul>
                <li><a href="home">Inicio</a></li>
                <li><a href="add">Añadir Producto</a></li>
                <li><a href="verify">Verificar Inventario</a></li>
                <li><a href="data_sales">Datos Historicos</a></li>
                <li><a href="report">Ventas del dia </a></li>
                <li><a href="venta_semanal">Ventas de la semana </a></li>
                <li><a href="cart">venta</a></li>
                <li><a <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></a></li>
              </ul>
            </nav>
          </div>
        </div>
    </div>


</body>


  </body>

</html>

app/views/home/metodohome.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

  </head>

<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

      <!-- Main -->
        <div id="main">
          <div class="inner">

            <!-- Header -->
            <header id="header">
              <div class="logo">
                <a>Inventario Online</a>
              </div>
            </header>

            <!-- Banner -->
            <section class="main-banner">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="banner-content">
                      <div class="row">
                        <div class="col-md-12">
                          <div class="banner-caption">
                            <h4>Bienvenido a tu <em>Inventario Online</em> </h4>
                            <p>El lugar donde podras trabajar y manejar tu empresa de la mejor manera.</p>
                            
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>


          </div>
        </div>

      <!-- Sidebar -->
        <div id="sidebar">
          <div class="inner">             
            <!-- Menu -->
            <nav id="menu">
              <ul>
                <li><a href="home">Inicio</a></li>
                <li><a href="add">Añadir Producto</a></li>
                <li><a href="verify">Verificar Inventario</a></li>
                <li><a href="data_sales">Datos Historicos</a></li>
                <li><a href="report">Ventas del dia </a></li>
                <li><a href="venta_semanal">Ventas de la semana </a></li>
                <li><a href="cart">venta</a></li>
                <li><a <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></a></li>
              </ul>
            </nav>
          </div>
        </div>
    </div>

</body>


  </body>

</html>